---
# tasks file for apigee-opdk-setup-ansible-controller-backup
- name: Create backup folder
  file:
    path: backups
    state: directory

- name: Backup files
  fetch:
    src: "{{ item.dir }}/{{ item.name }}"
    dest: "backups/{{ item.name }}"
    flat: yes
  with_items:
  - { dir: "{{ apigee_config }}", name: license.txt }
  - { dir: "{{ apigee_config }}/apigee-opdk-custom-properties", name: custom-properties.yml }
  - { dir: "{{ apigee_security }}", name: credentials.yml }



#ansible_config: "{{ playbook_dir }}/ansible.cfg"
#local_workspace: "{{ playbook_dir }}/ansible"
#target_ansible_workspace: "{{ ansible_workspace | default(local_workspace) }}"
#library_dir: "{{ target_ansible_workspace }}/library"
#setup_dirs:
#- "{{ library_dir }}"
#- "{{ target_ansible_workspace }}/roles"
#- "{{ target_ansible_workspace }}/logs"
#- "{{ target_ansible_workspace }}/tmp"
#
#target_apigee_config_folder: "{{ apigee_config_folder | default(playbook_dir) }}"
#starter_templates:
#- { dest_path: "{{ target_apigee_config_folder }}/apigee-secure", file_name: credentials.yml }
#- { dest_path: "{{ target_apigee_config_folder }}/apigee", file_name: custom-properties.yml }
#
#pip_config:
#- { dest_path: "{{ target_apigee_config_folder }}/apigee", file_name: pip.conf }
#
#inventory_folder: "{{ playbook_dir }}/inventory"
