---
# tasks file for apigee-opdk-setup-ansible-controller-backup
- name: Fetch files
  import_role:
    name: apigee-fetch-files
  vars:
    download_pattern: '{{ target_download_pattern }}'
    download_folder: "{{ target_download_folder }}"
